[package]
name = "algorithms"
version = "1.0.0"
authors = ["Kousuke Takaki <u7693@protonmail.com>"]
license = "MIT"
repository = "https://github.com/u7693/algorithms.git"
edition = "2018"

[dependencies]
